### ISSUE TITLE
pip install problem

### ISSUE THREAD

**Issue by redbobcat** [tmolteno/python-necpp#12]
Hello. Trying to install python-necpp with pip, and pip gives this.

'creating build/bdist.linux-x86_64/wheel/necpp-1.7.3.2.data/data/examples
  error: can't copy '../necpp_src/example/test.py': doesn't exist or not a regular file
  
  ----------------------------------------
  Failed building wheel for necpp'
 and in the end
'running install_data
    error: can't copy '../necpp_src/example/test.py': doesn't exist or not a regular file
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-HzMynH/necpp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-iaoCNk-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-HzMynH/necpp/
'

**Comment by tmolteno** [comment]
This has been fixed by the latest commits.
