### ISSUE TITLE
install for python 3

### ISSUE THREAD

**Issue by meinradr** [tmolteno/python-necpp#13]
Hi, I try to install PyNEC for Python 3 on Linux Mint 18.3. With the method described in the readme.md. It only installs the python 2 library. Is there an argument for installing for Python 3?
I also tried installing with PIP3 but I get a compiler error:

PyNEC_wrap.cxx:3062:27: fatal error: src/math_util.h: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

pip3 source file: https://files.pythonhosted.org/packages/11/16/8004bac8412d1cc501ef0cc78b4935086f502711c2db711a2c839aeeeeae/PyNEC-1.7.3.1.tar.gz

**Comment by tmolteno** [comment]
Thanks for the report. I'll have a look but a little swamped at the moment so may take a few days

**Comment by tmolteno** [comment]
This should have been fixed in the latest versions on PyPi
