### ISSUE TITLE
Weird impedance for a regular dipole

### ISSUE THREAD

**Issue by afiskon** [tmolteno/python-necpp#17]
I'm using Python 3.7.2 on MacOS Catalina 10.15.3. python-necpp 1.7.3.5 was installed using virtualenv + pip3:
```
pip3 install necpp
```
An example on https://pypi.org/project/necpp/ was rewritten a little to model a dipole on 14 Mhz frequency, 10 meters above the ground:

```
#!/usr/bin/env python3

import necpp

def handle_nec(result):
  if (result != 0):
    print(necpp.nec_error_message())

def impedance(frequency):
  nec = necpp.nec_create()
  handle_nec(necpp.nec_wire(nec, 1, 17, 0, -5.0, 10.0, 0, 5.0, 10.0, 0.001, 1, 1))
  # handle_nec(necpp.nec_geometry_complete(nec, 1, 0))
  handle_nec(necpp.nec_geometry_complete(nec, 1))
  handle_nec(necpp.nec_gn_card(nec, 1, 0, 0, 0, 0, 0, 0, 0))
  handle_nec(necpp.nec_fr_card(nec, 0, 1, frequency, 0))
  handle_nec(necpp.nec_ex_card(nec, 0, 0, 1, 0, 1.0, 0, 0, 0, 0, 0))
  handle_nec(necpp.nec_rp_card(nec, 0, 90, 1, 0,5,0,0, 0, 90, 1, 0, 0, 0))
  result_index = 0

  z = complex(necpp.nec_impedance_real(nec,result_index),
              necpp.nec_impedance_imag(nec,result_index))

  necpp.nec_delete(nec)
  return z

z = impedance(frequency = 14.0)
print("Impedance \t(%6.1f,%+6.1fI) Ohms" % (z.real, z.imag))
```

The impedance should be somewhere around 50..72 Ohm, but it's not even close:
```
Impedance 	(1162.6,-3578.8I) Ohms
```

As a side note an original example passes two arguments to nec_geometry_complete while according to http://tmolteno.github.io/necpp/libnecpp_8h.html#a8b6825e0707240cb673bd5ad9166a6ba there is only one argument.

**Comment by afiskon** [comment]
OK, I did the test once again on Ubuntu 18.04.4 LTS with Python 3.6.9 ans the result is the same. It's not impossible that I'm using the library incorrectly, but after checking the documentation for a while I don't see what's wrong.

**Comment by afiskon** [comment]
The dipole.py example ( https://github.com/tmolteno/python-necpp/blob/master/PyNEC/example/dipole.py ) works as expected, thus there is obviously a mistake somewhere in my code. I believe the tricky part is to find the right segment that will be used as a feed point, see line 35 in dipole.py

**Comment by mike6000** [comment]
Perhaps you are feeding the antenna in the end instead of in the middle? That could possibly explain the high impedance. You need to specify what segment the ex card should operate on. If you have 11 segments then you should excite segment 5 (middle segment).
