### ISSUE TITLE
Unclear difference between PyNEC and necpp python module

### ISSUE THREAD

**Issue by kaklik** [tmolteno/python-necpp#2]
Why the some source code examples import necpp and other handle the NEC by this
from PyNEC import *
(as TART antenna simulator does)

What is up to date method? 
Thanks

**Comment by tmolteno** [comment]
There are two Python wrappers. One wraps the c style API called necpp. The other wraps the C++ API and is called PyNEC - this is automatically generated from the C++ code, and is the new style that I would like to continue. I will attempt to clarify this in the docs (a little short of time at the moment though).

Kind Regards

**Comment by kaklik** [comment]
Thank you. I will continue using the PyNEC from this repository.  The source code seems to be more update than copy of the code in: https://github.com/tmolteno/necpp/tree/master/Python/PyNEC

**Comment by tmolteno** [comment]
Hi There. I have cleaned up the old code from the necpp (main) repository, and put a readme pointing to the new python-necpp repo (this one).
